; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Sun Aug 07 2022 10:28:28 GMT-0700 (Pacific Daylight Time)
M561 ; clear any bed transform


var dock0 = sensors.gpIn[10].value
var dock1 = sensors.gpIn[11].value
var dock2 = sensors.gpIn[12].value
var dock3 = sensors.gpIn[13].value
var undockedTools = ""
var cancelMessage = "Cancelling, one or more tools undocked: "
if { var.dock0 == 0 }
    set var.undockedTools = var.undockedTools ^ "0"
    set var.cancelMessage = var.cancelMessage ^ "0"
if { var.dock1 == 0 }
    set var.undockedTools = var.undockedTools ^ "1"
    if #var.undockedTools >= 1
        set var.cancelMessage = var.cancelMessage ^ ", "     
    set var.cancelMessage = var.cancelMessage ^ "1"
if { var.dock2 == 0 }
    if #var.undockedTools >= 1
        set var.cancelMessage = var.cancelMessage ^ ", "     
    set var.undockedTools = var.undockedTools ^ "2"
    set var.cancelMessage = var.cancelMessage ^ "2"
if { var.dock3 == 0 }
    if #var.undockedTools >= 1
        set var.cancelMessage = var.cancelMessage ^ ", "     
    set var.undockedTools = var.undockedTools ^ "3"
    set var.cancelMessage = var.cancelMessage ^ "3"

set var.undockedTools = ""
if #var.undockedTools > 0    
    M291 P{var.cancelMessage}
elif #var.undockedTools == 0
    ;M291 P"All tools docked"

    var caxis = move.axes[6].userPosition
    var currentTool = state.currentTool
    var safeC = 121

    if { var.caxis != var.safeC }
        var message = "Tool retainer not homed, refusing to go, C at " ^ {var.caxis}
        M291 P{var.message} S0 T2

    elif { var.currentTool != -1 }
        M291 S0 T2 P{"Tool is active"}    


    else
        ; 3 point probe
        G91
        G1 H2 Z10
        G90

        G53 G1 X5 Y5 F12000 
        G30 P0 X5 Y5 Z-9999 K0 


        G53 G1 X5 Y295 F12000 
        G30 P1 X5 Y295 Z-9999 K0 

        

        G53 G1 X335 Y147.5 F12000
        G30 P2 X335 Y147.5 Z-9999 S0 K0
        G53 G1 Z15
        
        
else
    M291 P"Can't inspect tools"
M99     