 ; Configuration file for Duet 3 MB 6HC (firmware version 3.3)
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Sun Aug 07 2022 12:40:33 GMT-0700 (Pacific Daylight Time)


; startup variables
global fan_t0 = -1
global fan_t1 = -1
global fan_t2 = -1
global fan_t3 = -1

M576 S0
M952 B0 S1000
; General preferences
M575 P1 S1 B57600                                                     ; enable support for PanelDue
G90                                                                   ; send absolute coordinates...
M83                                                                   ; ...but relative extruder moves
M550 P"Duet 3"                                                        ; set printer name
M669 K1                                                               ; select CoreXY mode
M586 C"*"
; Drives

M569 P0.0 S1 D2 H2000                                                       ; physical drive 0.0 goes reverse
M569 P0.1 S0 D2 H2000                                                        ; physical drive 0.1 goes forwards
M569 P0.2 S0 D2                                                       ; physical drive 0.2 goes forwards
M569 P0.3 S1 D2 H2000                                                        ; physical drive 0.3 goes forwards
M569 P0.4 S0 D2 H2000                                                        ; physical drive 0.4 goes reverse
M569 P0.5 S0 D2 H2000                                                        ; physical drive 0.0 goes reverse

M569 P1.0 S0 D2 H2000 
M569 P1.1 S0 D2 H2000 
M569 P1.2 S0 D2 H2000 

M569 P20.0 S0 D2                                                     ; physical drive 20.0 goes reverse
M569 P21.0 S0 D2                                                     ; physical drive 21.0 goes reverse
M569 P22.0 S0 D2                                                     ; physical drive 22.0 goes reverse
M569 P23.0 S0 D2                                                    ; physical drive 23.0 goes reverse

                                                      
;M584 Y0.0:0.4 X0.1:0.3 Z1.0:1.1:1.2 U1.0 V1.1 W1.2 C0.2 E20.0:21.0:22.0:23.0    ; set drive mapping
M584 Y0.0 X0.1 Z1.0:1.1:1.2 U1.0 V1.1 W1.2 C0.2 E20.0:21.0:22.0:23.0    ; set drive mapping

M350 E16  C8 Z64 U64 V64 W64 I0                             ; configure microstepping with interpolation                                                          
M350 X16 Y16 I1
M92 X80.00 Y80.00  U6400 V6400 W6400 Z6400 E674:674:674:647 C100        ; set steps per mm

M566 X1500.00 Y1500.00 U200.00 V200.00 W200.00 Z200 E300 C2    ; set maximum instantaneous speed changes (mm/min)

M203 X60000 Y60000 U600 V600 W600 Z600.00 E3600.00    ; set maximum speeds (mm/min)
M203 C5000

M201 X24000 Y24000.00 U200 V200 W200 Z200.00 E3000 C400; set accelerations (mm/s^2)


M906 X2000 Y2000 U2000 V2000 W2000 Z2000 C500 I30                          ; set motor currents (mA) and motor idle factor in per cent
M906 E800 I30
M84 S30                                                               ; Set idle timeout

M376 H20                                                              ; mesh taper off
M207 S1.5 F7200 Z0.2                                                  ; firmware retraction

; Axis Limits
M98 P"/sys/axis_limits.g"


; Endstops
M98 P"/sys/set_endstops.g"


; Heaters
M308 S0 P"temp0" Y"thermistor" T100000 B4138                          ; configure sensor 0 as thermistor on pin temp0
M950 H0 C"out1" T0                                                    ; create bed heater output on out0 and map it to sensor 0
M307 H0 B0 S1.00                                                      ; disable bang-bang mode for the bed heater and set PWM limit
M140 H0                                                               ; map heated bed to heater 0
M143 H0 S140                                                          ; set temperature limit for heater 0 to 140C
M308 S1 P"20.temp0" Y"PT1000"  ;Y"thermistor" T100000 B4725 C7.060000e-8         ; configure sensor 1 as thermistor on pin 20.temp0
M950 H1 C"20.out0" T1                                                 ; create nozzle heater output on 20.out0 and map it to sensor 1
M307 H1 B0 S1.00                                                      ; disable bang-bang mode for heater  and set PWM limit
M143 H1 S355                                                          ; set temperature limit for heater 1 to 350C
M308 S2 P"21.temp0" Y"PT1000" ;Y"thermistor" T100000 B4725 C7.060000e-8          ; configure sensor 4 as thermistor on pin 21.temp0
M950 H2 C"21.out0" T2                                                 ; create nozzle heater output on 21.out0 and map it to sensor 2
M307 H2 B0 S1.00                                                      ; disable bang-bang mode for heater  and set PWM limit
M143 H2 S355                                                          ; set temperature limit for heater 2 to 350C
M308 S3 P"22.temp0" Y"PT1000" ; Y"thermistor" T100000 B4725 C7.060000e-8          ; configure sensor 3 as thermistor on pin 22.temp0
M950 H3 C"22.out0" T3                                                 ; create nozzle heater output on 22.out0 and map it to sensor 3
M307 H3 B0 S1.00                                                      ; disable bang-bang mode for heater  and set PWM limit
M143 H3 S355                                                          ; set temperature limit for heater 3 to 350C
M308 S4 P"23.temp0" Y"PT1000" ;Y"thermistor" T100000 B4725 C7.060000e-8          ; configure sensor 4 as thermistor on pin 23.temp0
M950 H4 C"23.out0" T4                                                 ; create nozzle heater output on 23.out0 and map it to sensor 4
M307 H4 B0 S1.00                                                      ; disable bang-bang mode for heater  and set PWM limit
M143 H4 S355                                                          ; set temperature limit for heater 4 to 350C

; Fans
M950 F0 C"20.out2+out2.tach" k2 Q30                                            ; create fan 0 on pin 20.out2 and set its frequency
M106 P0 S0 H1 T80:80 C"Cooler 0"                                         ; set fan 0 value. Thermostatic control is turned on
M950 F1 C"20.out1+out1.tach"  Q12000
M106 P1 S0 H-1 C"Blower 0"                                            ; set fan 1 value. Thermostatic control is turned off
M950 F2 C"21.out2+out2.tach" Q500                                              ; create fan 2 on pin 21.out2 and set its frequency
M106 P2 S0 H2 T80:80 C"Cooler 1"                                         ; set fan 2 value. Thermostatic control is turned on
M950 F3 C"21.out1+out1.tach" k2 Q30
M106 P3 S0 H-1 C"Blower 1"                                            ; set fan 3 value. Thermostatic control is turned off
M950 F4 C"22.out2+out2.tach" Q500                                              ; create fan 4 on pin 22.out2 and set its frequency
M106 P4 S1 H3 T80:80 C"Cooler 2"                                         ; set fan 4 value. Thermostatic control is turned on
M950 F5 C"22.out1+out1.tach" k2 Q30                                            ; create fan 5 on pin 22.out1 and set its frequency
M106 P5 S0 H-1 C"Blower 2"                                            ; set fan 5 value. Thermostatic control is turned off
M950 F6 C"23.out2+out2.tach" Q500                                              ; create fan 6 on pin 23.out2 and set its frequency
M106 P6 S1 H4 T80:80 C"Cooler 3"                                         ; set fan 6 value. Thermostatic control is turned on
M950 F7 C"23.out1+out1.tach" k2 Q30                                            ; create fan 7 on pin 23.out1 and set its frequency
M106 P7 S0 H-1 C"Blower 3"                                            ; set fan 7 value. Thermostatic control is turned off
;M950 F8 C"duex.fan8" Q16000
;M106 P8 C"MCU Cooler" S1 H0 T40:40

M950 F16 C"out9" Q250
M106 P16 S0 H-1 C"CPAP" X65

; Custom settings are not defined

; Miscellaneous
M501                                                                  ; load saved parameters from non-volatile memory
M911 S10 R11 P"M913 X0 Y0 G91 M83 G1 Z3 E-5 F1000"                    ; set voltage thresholds and actions to run on power loss




M302 R0 ; allow cold retractions

M915 t2000 p0.0 s64
M915 t2000 p0.1 s64
M915 t2000 p1.0 s64
M915 t2000 p1.1 s64

M915 t2000 p3
M915 t2000 p4
M915 t2000 p5

; create tools
M563 P0 S"Tool 0" D0 H1 F1                                            ; define tool 0
M563 P1 S"Tool 1" D1 H2 F3                                            ; define tool 1
M563 P2 S"Tool 2" D2 H3 F5                                            ; define tool 2
M563 P3 S"Tool 3" D3 H4 F7                                            ; define tool 3


; configure tool io
M98 P"/sys/tools.g"
M98 P"/sys/triggers.g"

M98 P"/sys/accelerometers.g"

G21  ; millimeters


M98 P"/sys/config-user.g"

; enable buttons
M98 P"/sys/control_panel.g"
