; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Tue Jul 21 2020 18:20:38 GMT-0700 (Pacific Daylight Time)

M98 P"homec.g"
;m906 X1800 Y1800
M98 P"homey.g"


M98 P"homex.g"
;m906 x1000 y1000
M98 P"homez.g"

G1 X-20 Y275 Z10 F12000