/**
 * The defect catalogue. Where the invariant register answers "what must hold",
 * this answers "what is known to be wrong" — findings from the sweep, and any
 * other defect we decide not to fix on the spot.
 *
 * Generated into DEBT.md, in USER_AUDIT.md's format, for the same reason the
 * register is generated: its predecessor docs/invariant-ledger.md (deleted
 * 2026-07-31) was kept by hand, went 136 commits stale and silently lost three
 * of its four rows. A catalogue nothing regenerates is a catalogue that decays.
 *
 * Two inputs, one output. A defect with a code home is declared beside the
 * broken code, so deleting the code deletes the entry; a defect with no code
 * home (tooling, environment, or a fault in a test file, which src-only
 * scanning cannot see) goes in debt.json.
 */
import { readRecords } from "./blocks.ts";
import type { Problem } from "./check.ts";

export const STATUSES = ["fixed", "partial", "todo", "deferred", "corner"] as const;
export type Status = (typeof STATUSES)[number];

/** Badge text, matching USER_AUDIT.md exactly so the two read as one system. */
const BADGE: Readonly<Record<Status, string>> = {
	fixed: "✅",
	partial: "🟡",
	todo: "❌",
	deferred: "🟦",
	corner: "🔬",
};

const LEGEND: readonly (readonly [string, string])[] = [
	["✅ **FIXED**", "Fixed (file / commit cited)"],
	["🟡 **PARTIAL**", "Mitigated but incomplete — sub-cases remain"],
	["❌ **TODO**", "Known broken, not yet addressed"],
	["🟦 **DEFERRED**", "Deliberately postponed; the reason is the Fix column"],
	["🔬 **CORNER CASE**", "Narrow edge case that is easy to get wrong; verify with a fixture"],
];

export interface RawBroken {
	readonly slug: string;
	readonly status: string | undefined;
	readonly what: string | undefined;
	readonly fix: string | undefined;
	readonly where: string | undefined;
	readonly file: string;
	readonly line: number;
}

declare const valid: unique symbol;

/** Only checkBroken produces this, so renderDebt cannot be handed a bad entry. */
export type BrokenEntry = {
	readonly slug: string;
	readonly status: Status;
	readonly what: string;
	readonly fix: string | undefined;
	readonly where: string;
} & { readonly [valid]: true };

export function parseBroken(text: string, file: string): RawBroken[] {
	return readRecords(text, "broken", ["status", "what", "fix", "where"]).map(r => ({
		slug: r.lead,
		status: r.fields["status"],
		what: r.fields["what"],
		fix: r.fields["fix"],
		where: r.fields["where"],
		file,
		line: r.line,
	}));
}

const isStatus = (value: string): value is Status => (STATUSES as readonly string[]).includes(value);

export function checkBroken(raw: readonly RawBroken[]): { entries: BrokenEntry[]; problems: Problem[] } {
	const entries: BrokenEntry[] = [];
	const problems: Problem[] = [];
	const seen = new Map<string, RawBroken>();

	for (const item of raw) {
		const fail = (message: string): void => void problems.push({ file: item.file, line: item.line, message });

		const prior = seen.get(item.slug);
		if (prior !== undefined) {
			fail(`duplicate defect id "${item.slug}" — already catalogued at ${prior.file}:${prior.line}`);
			continue;
		}
		if (item.status === undefined || item.status.trim() === "") {
			fail(`"${item.slug}" has no @status`);
			continue;
		}
		const status = item.status.trim().toLowerCase();
		if (!isStatus(status)) {
			fail(`"${item.slug}" has status "${status}" — expected one of ${STATUSES.join(", ")}`);
			continue;
		}
		if (item.what === undefined || item.what.trim() === "") {
			fail(`"${item.slug}" has no @what — an entry with no defect described is not an entry`);
			continue;
		}
		const fix = item.fix?.trim();
		if (status === "fixed" && (fix === undefined || fix === "")) {
			fail(`"${item.slug}" is marked fixed with no @fix — a fix with no account of it is not evidence`);
			continue;
		}

		seen.set(item.slug, item);
		entries.push({
			slug: item.slug,
			status,
			what: item.what.trim(),
			fix: fix === "" ? undefined : fix,
			where: item.where?.trim() ?? `${item.file}:${item.line}`,
		} as BrokenEntry);
	}

	return { entries, problems };
}

/** A cell may never contain a bare pipe, or it silently splits its own row. */
const cell = (text: string): string => text.replaceAll("|", "\\|").replaceAll("\n", " ");

export function renderDebt(entries: readonly BrokenEntry[]): string {
	const sorted = [...entries].sort((a, b) => (a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0));
	const open = sorted.filter(e => e.status !== "fixed").length;

	const lines: string[] = [
		"# Debt",
		"",
		"> **Generated by `packages/invariants` — DO NOT EDIT.**",
		"> Declare a defect beside the broken code with an `@broken` block, or — when",
		"> it has no code home — in `packages/invariants/debt.json`. Regenerate with",
		"> `pnpm --filter @dwc-ng/invariants generate`.",
		"",
		"Everything found broken and not fixed on the spot. Same badges and columns as",
		"`USER_AUDIT.md`, which catalogues what the *operator* reported; this one",
		"catalogues what the *code* turned out to be doing.",
		"",
		`**${sorted.length} catalogued · ${open} still open.**`,
		"",
	];

	for (const [badge, meaning] of LEGEND) lines.push(`| ${badge} | ${meaning} |`);
	lines.splice(lines.length - LEGEND.length, 0, "| Badge | Meaning |", "|:------|:--------|");

	lines.push("", "| Status | Bug | Fix |", "|--------|-----|-----|");
	for (const e of sorted) {
		const bug = `**\`${e.slug}\`** — ${cell(e.what)} <br>\`${cell(e.where)}\``;
		lines.push(`| ${BADGE[e.status]} | ${bug} | ${e.fix === undefined ? "—" : cell(e.fix)} |`);
	}

	return `${lines.join("\n").trimEnd()}\n`;
}
