/**
 * The register's bytes. Sorted here rather than at the call site so the output
 * cannot depend on how the declarations arrived.
 */
import { MIN_RUNG, type Declaration } from "./check.ts";

export function renderRegister(declarations: readonly Declaration[], ceiling: number): string {
	const sorted = [...declarations].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
	const debts = sorted.filter(d => d.rung < MIN_RUNG);

	const lines: string[] = [
		"# Invariant register",
		"",
		"> **Generated by `packages/invariants` — DO NOT EDIT.**",
		"> Declarations live beside the mechanisms that enforce them; regenerate with",
		"> `pnpm --filter @dwc-ng/invariants generate`.",
		"",
		"Every invariant this repo knows about, extracted from the `@invariant` blocks",
		"in source. An invariant is a property that must hold across all executions,",
		"whose violation is a defect rather than a preference.",
		"",
		"**Completeness of discovery is rung 4.** No generator can detect an invariant",
		"nobody wrote down. A lint catches the syntactic tells (\"callers must\",",
		"\"should\", \"by convention\"); everything past that is human judgement. This",
		"register is exhaustive over what has been *declared*, not over what exists.",
		"",
		"**This describes HEAD, not history.** Declarations began at the 2026-07-31",
		"sweep; the register carries no record of what a rung used to be. For the 138",
		"commits between the old hand-kept ledger's last update and that sweep, two",
		"things were checked rather than assumed: branded types in `src` went 5 -> 5",
		"and invariant claim mentions 13 -> 23, so no mechanism was deleted and no",
		"claim was lost in the gap. From here the ratchets make a dropped rung visible",
		"in the diff that drops it.",
		"",
		`**Totals:** ${sorted.length} invariants · ${sorted.length - debts.length} at rung ${MIN_RUNG} or above · ` +
			`${debts.length} below rung ${MIN_RUNG} (ceiling ${ceiling}).`,
		"",
	];

	let namespace = "";
	for (const d of sorted) {
		if (d.namespace !== namespace) {
			namespace = d.namespace;
			lines.push(`## ${namespace}`, "");
		}
		lines.push(`### \`${d.id}\` — rung ${d.rung}`, "");
		lines.push(`**Mechanism.** ${d.mechanism}`, "");
		lines.push(`**Why.** ${d.why}`, "");
		if (d.debt !== undefined) lines.push(`**Debt — promotion.** ${d.debt}`, "");
		lines.push(`\`${d.file}:${d.line}\``, "");
	}

	return `${lines.join("\n").trimEnd()}\n`;
}
