// Story: register/INDEX.md's contract, made mechanical (spec I2, I13): the index is derived, never authored.
import fs from 'node:fs';
import path from 'node:path';
import { parseRuleFile } from './frontmatter.mjs';

export function readRules(rulesDir) {
  return fs.readdirSync(rulesDir).filter((f) => f.endsWith('.md')).sort()
    .map((f) => parseRuleFile(fs.readFileSync(path.join(rulesDir, f), 'utf8'), f));
}

export function generateIndex(rulesDir) {
  const entries = fs.readdirSync(rulesDir).filter((f) => f.endsWith('.md')).sort()
    .map((f) => ({ name: f, text: fs.readFileSync(path.join(rulesDir, f), 'utf8') }));
  return generateIndexFrom(entries);
}

// entries: [{name, text}] — the rule files being indexed, already read (spec I28: lets a caller
// build the index from the STAGED tree instead of the working tree). Pure; no I/O.
export function generateIndexFrom(entries) {
  const files = entries.map((e) => parseRuleFile(e.text, e.name));
  const known = new Set(files.flatMap((f) => f.sections.map((s) => `rules/${f.name} § ${s.heading}`)));
  const rows = files.map((f) => `| rules/${f.name} | ${f.status} | ${f.rules} | ${f.sections.map((s) => s.heading).join('; ')} |`);
  const sup = [];
  for (const f of files) for (const s of f.supersedes) {
    const key = `rules/${f.name} § ${s.section}`;
    if (!known.has(key)) throw new Error(`${f.name}: supersedes names a section that does not exist: '${s.section}'`);
    sup.push({ superseded: key, by: s.by, date: s.date });
  }
  sup.sort((a, b) => a.superseded.localeCompare(b.superseded));
  const out = ['# Register index', '', 'Generated by machinery — do not edit; run /machinery:reindex.', '',
    '| File | Status | Rules | Sections |', '|---|---|---|---|', ...rows, '', '## Supersession', '',
    '| Superseded | By | Date |', '|---|---|---|', ...sup.map((s) => `| ${s.superseded} | ${s.by} | ${s.date} |`), '',
    '## Superseded by (derived)', '', '| Section | Supersedes | Date |', '|---|---|---|',
    ...[...sup].sort((a, b) => a.by.localeCompare(b.by)).map((s) => `| ${s.by} | ${s.superseded} | ${s.date} |`), ''];
  return out.join('\n');
}

export const readIndex = (file) => (fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null);
